### ISSUE TITLE
nimsuggest session not starting

### ISSUE THREAD

**Issue by rokf** [xomachine/textadept-nim#1]
Hey, I've got a little problem here. The `nimsuggest` session starts only when I run textadept via terminal (like `cd` to the folder and `./textadept`).

Its because of the default `stdin` mode?

**Comment by xomachine** [comment]
b2d831bc37c0c55ae1313f24035d15decdd68a77 should fix the problem. Could you check it?

**Comment by rokf** [comment]
It does not fix the problem. I'm trying some stuff myself. `local nm = io.popen("nim"):read()` and `local nms = io.popen("nimsuggest"):read()` are both alright.

**EDIT**:
It actually didn't work. If I run those two commands from a textadept that was ran from somewhere else than a terminal it does not work. There is a problem on my side.

**EDIT #2**:
Need to find where lua/textadept is looking for the **PATH** variable because that one is wrong when I don't run via terminal.

**Comment by xomachine** [comment]
Seems like I fixed another bug. =)
Latest commits should fix this bug also.
Thank you!
**UPD:** 
Your solution works for me, so now I cann't reproduce the bug. 

**UPD2:**
I finally figured out the problem origin. There was a some kind of race condition between nimsuggest executable (which prints to stdout) and plugin (which reads stdout). In some cases nimsuggest prints to stdout after the plugin reads it. In f9b3f9d855da8b87061d38d04e5e8f24c27e1417 I used blocking `read("*all")` call, so it should work properly now.

**Comment by rokf** [comment]
My issue was the **PATH**. I had to change it at the level of my login shell in **.profile**. I had to set the PATH in that file and now lua finds **nim** and **nimsuggest** when not ran from the terminal.

**Comment by xomachine** [comment]
Anyway, I've found some hidden problems while trying to reproduce your.

Does your answer mean that the issue can be considered as solved? Or are there any other problems related to plugin?

**Comment by rokf** [comment]
Solved. :smile:
